### ISSUE TITLE
Vagrant setup doesn't compile

### ISSUE THREAD

**Issue by hylje** [d-cent/freecoin#3]
Error message: 

```
Exception in thread \"main\" java.io.FileNotFoundException: Could not locate ns_tracker/core__init.class or ns_tracker/core.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```

Using vanilla repository, except for two changes:
- LEIN_SNAPSHOTS_IN_RELEASE is set for the jar create task in playbook (otherwise fails earlier to Lein being picky about unspecific versions)
- Vagrantfile uses a more recent Vbox image of Devuan (the old version is unavailable)

Lein may be right in that allowing non-date frozen snapshots in release is a bad idea, but in any case, the vagrant setup does not build in its present form.

**Comment by skuro** [comment]
Not sure about the compile error, which seems to be gone by now, but Vagrant still barfs due to

- the `.box` URL for Devuan is no longer accessible
- even when using a [valid URL](devuan_jessie_1.0.0-beta_amd64_vagrant.box) it still complaints that the network cannot be properly configured (same behaviour as [here](https://github.com/mitchellh/vagrant/issues/6426))

**Comment by jaromil** [comment]
I guess this is because Vagrant does not recognise Devuan. While there are workarounds to this, I'll file a PR for Vagrant to add a devuan plugin here https://github.com/mitchellh/vagrant/tree/master/plugins/guests it should be easy to recycle Debian's ignoring the systemd commands (which are still conditional as of now)

**Comment by skuro** [comment]
@jaromil sounds a reasonable explanation. Here's the actual error message I receive, which shows how Vagrant detects a `linux` guest OS, which [doesn't declare](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/linux/plugin.rb) the `configure_networks` capability:

```
Vagrant attempted to execute the capability 'configure_networks'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

**Comment by jaromil** [comment]
Just a brief heads-up we detected more problems in the old .box of Devuan-beta and now rolling a new Vagrant image together with @parazyd likely ready this week.

**Comment by aspasia** [comment]
@jaromil does the last commit solve the problem? Also is the README in ops up to date?

**Comment by jaromil** [comment]
The vagrant problem is solved but the documentation needs update. I'll do further work around the ops also to include stonecutter, meanwhile I guess this issue can be closed.
